### ISSUE TITLE
Querying annotations from multiple annotators simultaneously

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/ARCHIVE-lasair-lsst#113]
Occasionally we'd like to be able to query more than one annotation at the same time - e.g. everything that fastfinder classifies as KN and everything that 4MOST spectroscopically classified as KN.

Relatively simple solution is to exchange the radio button for another set of checkboxes on the query page.

**Comment by RoyWilliams** [comment]
I have thought of this, and its on my list. Multiple annotations, multiple watchlists, multiple areas. The difficult part is changing the code that checks and builds the SQL.

**Comment by RoyWilliams** [comment]
This is done now.
