### ISSUE TITLE
Missed objects in SN-like SQL query

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/ARCHIVE-lasair-lsst#116]
These objects (subsequently flagged by Pan-STARRS) are not being picked up by the SN-like candidates query, in spite of being clearly young and rising.  Ken to investigate.

https://lasair-iris.roe.ac.uk/object/ZTF21ackoehe/
https://lasair-iris.roe.ac.uk/object/ZTF21acjuwuk/

**Comment by RoyWilliams** [comment]
I think was about Lasair being offline at the time the alerts came through
