### ISSUE TITLE
Streaming queries are fed incompatible schemas when the owner changes the query

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/ARCHIVE-lasair-lsst#119]
End users will often be experimenting with the SQL that feeds their output to a stream.  But if a streaming query is constantly changing, incompatible key-value pairs are fed onto the Kafka queue.  Users doing such experiments often use random group_ids so that they can go back to the beginning of their stream to re-test.  But if they're renamed their columns, then new results get new column keys.

We could just tell them that they need to write try/catch blocks and ignore the KeyErrors, or maybe we could clear the cache if the query has changed.  Though if the Kafka cache is cleared then the user has to wait for a new event!

Anyway, raising this since it came up in a call.  At the very least I think we might need to document the usage scenarios to warn users that KeyErrors will happen if they alter their streaming queries.

**Comment by gpfrancis** [comment]
Was this fixed by https://github.com/lsst-uk/lasair-lsst-web/pull/8 or is there more to be done?

**Comment by RoyWilliams** [comment]
This is now fixed
