### ISSUE TITLE
Mock Kafka consumption for users testing streaming queries

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/ARCHIVE-lasair-lsst#120]
Users will constantly want to change their streaming queries.  We suggest that a test system is setup for these users to allow them to query the database, the result of which is fed onto a new Kafka test topic.

We need a fake Kafka consumer for testing purposes. (Not actually a consumer, but simulates the results by a direct read of the central database.)  See issue #119.

**Comment by RoyWilliams** [comment]
The problem here has been solved, but not by this mechanism. When a streaming query is modified, the kafka topic is deleted, then remade using 10 results from the new query.
