### ISSUE TITLE
Lasair settings - move configuration IP addresses and ports out of Hashicorp Vault to Ansible

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/ARCHIVE-lasair-lsst#137]
Config IPs and config ports are buried in Hashicorp Vault secrets.  These should really be pulled by Ansible from Ansible variables or Ansible host groups (since these will change for every deployment).  Burying them into the Vault secrets makes new (e.g. development & test) deployments very difficult without lots of post install manual fixes.

**Comment by RoyWilliams** [comment]
This is all handled properly in lasair-deploy
