### ISSUE TITLE
Query SN-like candidates in last 14 days - 1054 (42S22): Unknown column 'objects.latestrmag' in 'field list'

### ISSUE THREAD

**Issue by JohnAstronomer** [lsst-uk/ARCHIVE-lasair-lsst#140]
The query at https://lasair-iris.roe.ac.uk/query/202/ returns the error '1054 (42S22): Unknown column 'objects.latestrmag' in 'field list'' . latestmag does not appear in the schema at https://lasair-iris.roe.ac.uk/schema should the field be rmag though it is not clear if this is the latest value or a value at time past.

**Comment by RoyWilliams** [comment]
That is correct, the latest magnitudes are "gmag" and "rmag"
