### ISSUE TITLE
Query on last 1000 objects rather than first 1000

### ISSUE THREAD

**Issue by JohnAstronomer** [lsst-uk/ARCHIVE-lasair-lsst#142]
The query has a limit on the number of objects returned which defaults to the first 1000. Would it be possible to revise this so the query can be run on a selected number of last entries in the database instead. The latest entries are probably more relevant when testing a query.

I presume that this will be by object ID but there might be other options that others would want ?? Such as last observation date.

**Comment by RoyWilliams** [comment]
The most recent observation date is the attribute "jdmax". If you want results returned with newest first, just add "ORDER BY jdmax DESC" to the end of the query.

**Comment by JohnAstronomer** [comment]
Thanks Roy, That works fine so this issue can be closed - wish I remembered more SQL !
