### ISSUE TITLE
Use of db name in db schema

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#145]
Database SQL schema should not reference the database name explicitly (e.g. "ztf"). Removing this will make them easier to use, match the JSON and avoid a future problem when we want to call the database something else.

Example of the issue on line 1 of https://github.com/lsst-uk/lasair-lsst/blob/develop/utility/schema/sherlock_classifications.sql The "USE ztf" can be safely removed.

**Comment by RoyWilliams** [comment]
The CREATE TABLE is built from code. Perhaps we can change just this line and rerun the conversions?
https://github.com/lsst-uk/lasair-lsst/blob/main/utility/schema/convert.py#L42
