### ISSUE TITLE
Use unit tests for all code

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#15]

**Comment by tms-epcc** [comment]
See [lasair-lsst/#73](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/73)

**Comment by tms-epcc** [comment]
30JUN/21
 - @RoyWilliams and @tms-epcc agreed this is being dealt with in [Cycle-4](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/67) under [Review and set up software engineering process for build phase](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/73)

**Comment by tms-epcc** [comment]
As agreed at [Lasair SE process meeting on 22/SEP/21](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2767814661/Lasair+SE+process+meeting+-+22+SEP+21)  

@RoyWilliams  / @gpfrancis  To work together on the annotation ingest code such that unit tests are created and their execution automated via Jenkins. Report on this at the next meeting. 

@genghisken  / @thespacedoctor  To work together on the Cassandra data inserts (replace code with pre-cooked code) such that unit tests are created and their execution automated via Jenkins. Report on this at the next meeting.

**Comment by tms-epcc** [comment]
For tests see https://github.com/lsst-uk/lasair4/tree/main/tests
