### ISSUE TITLE
Order in filter does not work

### ISSUE THREAD

**Issue by JohnAstronomer** [lsst-uk/ARCHIVE-lasair-lsst#155]
In my query I have a line 'ORDER BY objects.objectId DESC' 

This works ok in a query both with & without the DESC

When converted to a filter this does not work - the results come out in random order.

I am more interested in new transients at present so having the latest first makes it easier to check new transients.

**Comment by RoyWilliams** [comment]
This is because the streaming query is inherently different from a static query. Results *always* come out in time order because thats what streaming means ....

**Comment by JohnAstronomer** [comment]
This is true if an email was sent for every alert but they are collected into one days worth so it is a lot easier to see the duplicates and the interesting ones by looking at the result in order.
