### ISSUE TITLE
Run the pipeline in full, in parallel

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#19]
Run the ingestion pipelin on openstack clusters, in a continuous way, not just the test topic

**Comment by gpfrancis** [comment]
Current status is that ingest and Sherlock stages are running on the ZTF alert stream. Intermediate topics are "ztf_ingest" and "ztf_sherlock".

**Comment by Zarquan** [comment]
@gpfrancis The section on Kafka experiments in this document might be useful.
https://www.overleaf.com/read/xjpxjdgwncrx
