### ISSUE TITLE
Update Sherlock output format

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#23]

**Comment by gpfrancis** [comment]
Depends on Sherlock 2.1.6

**Comment by RoyWilliams** [comment]
There is now a lite parameter added to the Sherlock transient_classifier object (Default False).

classifier = transient_classifier(
    log=log,
    settings=settings,
    ra=ra,
    dec=dec,
    name=name,
    verbose=verbose,
    updateNed=False,
    lite=True
)
classifications, crossmatches = classifier.classify()
Adding lite=True does 2 things:

Returns only the top-ranked matches in the crossmatches list, and
Returns only the most pertinent information for those top-ranked sources
This should drastically reduce the Sherlock footprint in the transient database.

Here is the lite column listing with example values:

transient_object_id : ATLAS17jed
association_type : SN
catalogue_table_name : NED D/SDSS/2MASS/GLADE/PS1
catalogue_object_id : NGC0716
catalogue_object_type : galaxy
raDeg : 28.248701
decDeg : 12.708479
separationArcsec : 31.06
northSeparationArcsec : -16.204
eastSeparationArcsec : -26.493
physical_separation_kpc : 8.52
direct_distance : 56.6
distance : 65.88
z : 0.02
photoZ : 0.02
photoZErr : 0.01
Mag : 17.41
MagFilter : r
MagErr : 0.0
classificationReliability : 2

**Comment by gpfrancis** [comment]
Done. Now sending alerts to ztf_sherlock again.
