### ISSUE TITLE
Ansible playbook for wrapper prerequisites

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#25]
Create a playbook for setting up necessary prerequisites for sherlock wrapper. Requires docker, docker-compose etc., see Narcissus for an example.

**Comment by tms-epcc** [comment]
14/JUL/21
- @gpfrancis explained this is currently blocked by a Sherlock issue

**Comment by tms-epcc** [comment]
06/OCT/21
- as discussed with @gpfrancis via email, this will get fixed as a result of the work  Gareth is doing on deployment generally in cycle 5.

**Comment by tms-epcc** [comment]
23/MAR/22 Lasair meeting
- See [lasair-deploy repo](https://github.com/lsst-uk/lasair-deploy)
- makes building new pipelines easier
- carries into cycle-6

**Comment by gpfrancis** [comment]
Superceded by work on https://github.com/lsst-uk/lasair-deploy
