### ISSUE TITLE
Build and document the control of multiple clusters

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#39]
How to start and stop the entire pipeline

**Comment by RoyWilliams** [comment]
Rubin uses ArgoCD. Ask Stelios.

**Comment by tms-epcc** [comment]
30/JUN/21
- @RoyWilliams and @tms-epcc agreed this is being dealt with as part of [Cycle-4](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/67) under [Review and set resilience plan](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/74)

**Comment by tms-epcc** [comment]
29/SEP/21
- this start/stop has been checked.
- Roy advised Ken what needed to done and Ken did this.
- details on how to this in [Lasair Principles of Operation](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2763161628/Lasair+Principles+of+Operation)
