### ISSUE TITLE
Multi-threaded sherlock wrapper

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#4]
Implement multi-threaded consumer and producer for the sherlock wrapper.

Lasair-dev not avalalble (Sept 2). Will work with Belfast install of Shelock.

**Comment by RoyWilliams** [comment]
Not a priority but will need doing at some point

**Comment by gpfrancis** [comment]
Avoiding a costly resubscribe on every batch largely addresses the problem here by reducing the time spent in Kafka to a small proportion of the total - attempting to improve further by overlapping with sherlock processing is likely not a big additional gain.
