### ISSUE TITLE
Fully automate the creation of cluster VMs

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#40]

**Comment by tms-epcc** [comment]
30/JUN/21
- @RoyWilliams and @tms-epcc agreed this is being dealt with in [Cycle-4](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/67) under [Architecture Development](https://app.zenhub.com/workspaces/lasair-5f75d02d91823488d74ec3f8/issues/lsst-uk/lasair-lsst/69)

**Comment by RoyWilliams** [comment]
See ansible scripts
https://github.com/lsst-uk/lasair-lsst/tree/master/ansible
https://github.com/lsst-uk/lasair-lsst-web/tree/master/ansible
