### ISSUE TITLE
A3.02 Architecture Prototyping

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#51]
For github original see https://github.com/lsst-uk/lasair-lsst/projects/1

----

At the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), it was agreed that @tms-epcc move the notes from the github kanban (see see https://github.com/lsst-uk/lasair-lsst/projects/1) to this epic ticket.  These notes are as follows. All were originally added by @gpfrancis.  

Question: should the Sherlock wrapper cache have a TTL or other process for invalidating old entries?

Question: should the Sherlock wrapper cache ORPHAN objects? (Don't think it does at present.)

Do we want to adopt a generic annotation format, if so do we want to update the Sherlock wrapper to use it and do we want to propose it be used more widely, e.g. at the CBW?

See comment from below from @gpfrancis as to the answers.

**Comment by tms-epcc** [comment]
At the [28/APR/21 Lasair internal review](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2331738150/Lasair+Cycle+4+Internal+Review), it was agreed that @tms-epcc move the notes from the github kanban (see see https://github.com/lsst-uk/lasair-lsst/projects/1) to this epic ticket.

**Comment by gpfrancis** [comment]
For the record, the answer to the first question was yes and I've promoted it to its own issue (see lsst-uk/lasair4#35) ; the second is not critical if the first is handled properly; and the answer to the third is yes and it's done.
