### ISSUE TITLE
Sherlock API should handle overload gracefully

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#55]
At present it will probably run out of memory and crash if overloaded. Should implement some kind of check or limit and wait or return an error if necessary.

**Comment by tms-epcc** [comment]
14/JUL/21
- @gpfrancis explained this is a normal, but not high priority, feature request. It will likely get dealt with in Cycle-4, but there is no urgent need so it might get delayed by higher priority issues.

**Comment by tms-epcc** [comment]
06/OCT/21
- as discussed with @gpfrancis via email, this is not a priority for Lasair cycle 5 and hence is moved into the backlog.

**Comment by gpfrancis** [comment]
Sherlock service to be integrated with rest of API, likely in cycle 7, which will make this issue obsolete.
