### ISSUE TITLE
Add cron-based "services" layer

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#59]
When watchlist or area is changed, must ensure that the cached MOC files are properly built before the night's run. Also check TNS for new entries and add them to watchlist, as well as crossmatch with past ZTF objects.

**Comment by RoyWilliams** [comment]
Has been running for 4 months on head node.

$ ssh ubuntu@192.41.108.34
1 */4 * * * python3 /home/ubuntu/lasair-lsst/services/TNS/poll_tns.py --pageSize=500 --inLastNumberOfDays=180
10 0 * * * python3 /home/ubuntu/lasair-lsst/services/areas/make_area_files.py
12 0 * * * python3 /home/ubuntu/lasair-lsst/services/watchlists/make_watchlist_files.py
~

**Comment by tms-epcc** [comment]
30/JUN/21
- @RoyWilliams and @tms-epcc  agreed this can be closed
