### ISSUE TITLE
Test topic with sherlock info included

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#62]
Please make a non-volatile topic that is a copy of the ztf_sherlock topic, with perhaps 50,000 alerts in it. We could call it speedtest_ztf_sherlock

**Comment by gpfrancis** [comment]
Created as ztf_test_sherlock

**Comment by RoyWilliams** [comment]
Both test topics are good. Thank you!
