### ISSUE TITLE
Set up and run external review

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#72]
- [x] Make plan
- [x] Make wiki page for external review : https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2609283073/Lasair+Cycle-4+External+Review
- [x] Approach externals
- [x] Fix date : 08/SEP/21 13:00 to 18:00
- [x] Fix attendee list
- [x] Design agenda, assign presentations
- [x] Prep advance material
- [x] Hold meeting, take [notes, actions](https://lsst-uk.atlassian.net/wiki/spaces/~524382153/pages/2746351638/Lasair+Cycle-4+mid-Project+Review+notes+and+actions+from+08+SEP+21)
- [x] Digest and debate at fortnightly meeting

**Comment by andyxerxes** [comment]
Some planning thoughts:

Date: late August/earlylate August/early Sept
- long enough for us to have something good to say
- enough time remaining in C4 to digest and use

Length:  half day (maybe afternoon for US folk?)

Externals:
* 1 scientist from SWG
* 1-2 from other Euro-brokers
* 1 from US project
* 1 external tech expert 
- EPCC engineer? 
- commercial DB person

Format:
some advance material
mostly presentations

Advance material
- revised Phase B plan
- wiki pages

Focus: everything 
functionality
technical implementation
UI, API

**Comment by andyxerxes** [comment]
Start by making wiki page for external review

**Comment by tms-epcc** [comment]
Note from meeting available at https://lsst-uk.atlassian.net/wiki/spaces/~524382153/pages/2746351638/Lasair+Cycle-4+mid-Project+Review+notes+and+actions+from+08+SEP+21
