### ISSUE TITLE
3 more attributes

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/ARCHIVE-lasair-lsst#81]
Please add three more attributes to the sherlock annotation that is passed to the filter module and then the MySQL. These are: 
major_axis_arcsec
_g
_r
These result from https://github.com/lsst-uk/lasair/issues/240 raised by Matt Nicholl.

**Comment by gpfrancis** [comment]
I think this is currently blocked by https://github.com/thespacedoctor/sherlock/issues/134

**Comment by thespacedoctor** [comment]
`major_axis_arcsec` has been added to Sherlock Lite (`_g` and `_r` will not be added ... see discussion in lsst-uk/lasair#240)

**Comment by gpfrancis** [comment]
This is fixed by the update to Sherlock 2.2.0.
