### ISSUE TITLE
Add public Kafka status to dashboard

### ISSUE THREAD

**Issue by gpfrancis** [lsst-uk/ARCHIVE-lasair-lsst#88]
Up/down status (at least) of public kafka broker should go on system health Grafana dashboard.

**Comment by RoyWilliams** [comment]
How to fix when broken

ssh to the VM (ubuntu@192.41.108.35) using the shared ssh key
“docker ps -a” to see what containers are running
note that both kafka and zookeeper containers are stopped
“docker logs <container> --tail 40” to see if there’s any obvious reason why they stopped
“docker container start <zookeeper container>”
check logs to make sure it’s running OK
“docker container start <kafka container>"
wait a few minutes for it to start up then test

**Comment by gpfrancis** [comment]
Added the blackbox prometheus exporter to check status of generic services.
