### ISSUE TITLE
Towards LSST: feasibility report

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/ARCHIVE-lasair-lsst#99]
- [x] Report started [here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2807037956/Handling+ZTF+and+handling+LSST)
- [x] Review started
- [x] Report finished

**Comment by tms-epcc** [comment]
@smarttgit will review the report

**Comment by RoyWilliams** [comment]
This report was discussed in a fortnightly meeting, and the proposed extensions in it are now part of the Revised Phase B Long Term Plan. #75
